import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ClientLayout from "./ClientLayout";
import { cookies } from "next/headers";
import { parseAccessToken } from "./util/auth";

const pretendard = localFont({
  src: "./../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const myCookie = await cookies();
  const { isLogin, payload } = parseAccessToken(myCookie.get("accessToken"));

  const me = isLogin
    ? {
        id: payload.id,
        nickname: payload.nickname,
      }
    : {
        id: "",
        nickname: "",
      };

  return (
    <ClientLayout
      fontVariable={pretendard.variable}
      fontClassName={pretendard.className}
      me={me}
    >
      {children}
    </ClientLayout>
  );
}
