version: 0.0
os: linux
files:
  # Copy deploy.zip from the bundle to the target directory
  - source: /
    destination: /home/ec2-user/app

permissions:
  - object: /home/ec2-user/app/scripts/start_app.sh
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu