/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put: operations["updateMyProfile"];
        post?: never;
        delete: operations["deleteMyProfile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post-id}/comments/{comment-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 댓글 수정
         * @description 댓글 내용을 수정합니다.
         */
        put: operations["updateComment"];
        post?: never;
        /**
         * 댓글 삭제
         * @description 댓글을 삭제합니다.
         */
        delete: operations["deleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 게시글 상세 조회
         * @description 상품 게시글의 상세 정보를 조회합니다.
         */
        get: operations["getPost"];
        /**
         * 상품 게시글 수정
         * @description 상품 게시글의 내용을 수정합니다.
         */
        put: operations["modify"];
        post?: never;
        /**
         * 상품 게시글 삭제
         * @description 상품 게시글을 삭제합니다.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["grantAdmin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notices/{notice-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateNotice"];
        post?: never;
        delete: operations["deleteNotice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/email/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendAuthenticationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/email/code/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyAuthenticationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploadFile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 파일 업로드
         * @description 새로운 파일을 업로드합니다.
         */
        post: operations["uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 글 목록 조회
         * @description 상품 게시글 목록을 조회합니다.
         */
        get: operations["getPosts"];
        put?: never;
        /**
         * 상품 게시글 작성
         * @description 상품 게시글을 작성합니다.
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post-id}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 댓글 작성
         * @description 상품에 댓글을 작성합니다.
         */
        post: operations["writeComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 상품 게시글 찜
         * @description 상품 게시글을 찜합니다.
         */
        post: operations["likePost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상품 구매 여부 조회
         * @description 로그인한 유저가 상품을 구매했는지 여부를 반환합니다.
         */
        get: operations["checkPurchased"];
        put?: never;
        /**
         * 상품 구매
         * @description 페이머니로 상품을 구매합니다.
         */
        post: operations["purchaseItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/room": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 목록 페이지 조회
         * @description 채팅방 목록을 HTML 페이지로 반환합니다.
         */
        get: operations["rooms"];
        put?: never;
        /**
         * 채팅방 생성
         * @description 상품 판매자와의 채팅방을 생성합니다.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/admin/{adminId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 관리자와의 채팅방을 생성합니다.
         * @description id를 가진 관리자와의 채팅방을 생성합니다.
         */
        post: operations["createRoomAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user-id}/ban": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 유저 정지
         * @description 특정 유저를 정지시킵니다.
         */
        post: operations["banUser"];
        delete: operations["unBanUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getNotices"];
        put?: never;
        /**
         * 공지사항 등록
         * @description 새로운 공지사항을 등록합니다.
         */
        post: operations["writeNotice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/recently-viewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 조회한 상품 조회
         * @description 최근 조회한 상품들을 조회합니다.
         */
        get: operations["getRecentlyViewPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 작성한 상품 게시글 조회
         * @description 내가 작성한 상품 게시글을 조회합니다.
         */
        get: operations["getMyPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/my/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 판매한 상품 게시글 리스트 조회
         * @description 내가 판매한 상품 게시글의 목록을 조회합니다.
         */
        get: operations["getMySales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/my/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 구매한 상품 게시글 리스트 조회
         * @description 내가 구매한 상품 게시글의 목록을 조회합니다.
         */
        get: operations["getMyPurchases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/my/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내가 판매한 상품 게시글 리스트 조회
         * @description 내가 판매한 상품 게시글의 목록을 조회합니다.
         */
        get: operations["getMyFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 승인
         * @description PG사에 결제 승인을 요청합니다. PG사 서버로부터 리다이렉트된 요청을 받아 PG사로 결제 승인 API를 호출합니다.
         */
        get: operations["requestPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 결제 메타데이터 저장
         * @description 결제흐름 진행 전 메타데이터를 저장합니다.
         */
        get: operations["saveMetaData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 사용자 토큰 조회
         * @description 사용자를 판단하기 위한 토큰을 생성해 반환합니다.
         */
        get: operations["getUserInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 검색
         * @description 특정 유저가 속한 채팅방을 검색합니다.
         */
        get: operations["findChatRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 조회
         * @description 유저가 속한 채팅방을 모두 조회합니다.
         */
        get: operations["getUserRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/room/{roomId}/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 상세 페이지 조회
         * @description 채팅방 상세 페이지를 HTML로 반환합니다.
         */
        get: operations["showRoomDetailPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅방 메세지 조회
         * @description 채팅방의 모든 메시지를 조회합니다.
         */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        /**
         * 채팅방을 삭제합니다.
         * @description 유저가 속한 채팅방을 id로 삭제합니다.
         */
        delete: operations["deleteRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 카테고리 작성
         * @description 존재하는 카테고리 목록을 조회합니다.
         */
        get: operations["getCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUserList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/notices/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최신 공지사항 조회
         * @description 최신 공지사항 5개를 조회합니다.
         */
        get: operations["getLatestNotices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/posts/{post-id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 게시글 삭제
         * @description 게시글을 삭제합니다.
         */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RsDataVoid: {
            code: string;
            message: string;
            data: Record<string, never>;
        };
        UserUpdateRequest: {
            nickname?: string;
            address?: string;
            profileUrl?: string;
            email?: string;
        };
        RsDataUserDto: {
            code: string;
            message: string;
            data: components["schemas"]["UserDto"];
        };
        UserDto: {
            id?: string;
            username?: string;
            email?: string;
            nickname?: string;
            address?: string;
            profileUrl?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
            /** Format: int32 */
            cash?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            blocked?: boolean;
            /** Format: int32 */
            blockedCount?: number;
        };
        UpdateCommentReqBody: {
            content?: string;
        };
        RsDataUpdateCommentResBody: {
            code: string;
            message: string;
            data: components["schemas"]["UpdateCommentResBody"];
        };
        UpdateCommentResBody: {
            content?: string;
            author?: components["schemas"]["UserDto"];
        };
        ProductPostModifyForm: {
            productName?: string;
            /** Format: int32 */
            productPrice?: number;
            title?: string;
            content?: string;
            categoryIds?: number[];
            imageUrlList?: string[];
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
        };
        ProductPostResponse: {
            id?: string;
            writerId?: string;
            writerName?: string;
            productName?: string;
            /** Format: int32 */
            productPrice?: number;
            title?: string;
            content?: string;
            imageUrls?: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            categories?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            likedCount?: number;
        };
        RsDataProductPostResponse: {
            code: string;
            message: string;
            data: components["schemas"]["ProductPostResponse"];
        };
        Category: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        Comment: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            id?: string;
            target?: components["schemas"]["ProductPost"];
            author?: components["schemas"]["User"];
            content?: string;
        };
        GrantedAuthority: {
            authority?: string;
        };
        ProductCategory: {
            /** Format: int64 */
            id?: number;
            productPost?: components["schemas"]["ProductPost"];
            category?: components["schemas"]["Category"];
        };
        ProductPost: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            id?: string;
            productName?: string;
            /** Format: int32 */
            productPrice?: number;
            buyer?: components["schemas"]["User"];
            title?: string;
            content?: string;
            image_urls?: string;
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            likeCount?: number;
            /** @enum {string} */
            status?: "RESERVED" | "AVAILABLE" | "PURCHASED";
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            productCategories?: components["schemas"]["ProductCategory"][];
            writer?: components["schemas"]["User"];
            commentList?: components["schemas"]["Comment"][];
            available?: boolean;
        };
        RsDataUser: {
            code: string;
            message: string;
            data: components["schemas"]["User"];
        };
        User: {
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            id?: string;
            username?: string;
            password?: string;
            email?: string;
            nickname?: string;
            address?: string;
            profileUrl?: string;
            /** Format: int32 */
            cash?: number;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
            blocked?: boolean;
            /** Format: int32 */
            blockedCount?: number;
            purchasedProducts?: components["schemas"]["ProductPost"][];
            writtenProducts?: components["schemas"]["ProductPost"][];
            wroteComments?: components["schemas"]["Comment"][];
            admin?: boolean;
            authorities?: components["schemas"]["GrantedAuthority"][];
            memberAuthoritiesAsString?: string[];
        };
        UpdateNoticeReq: {
            title?: string;
            content?: string;
        };
        AdminResBody: {
            id?: string;
            nickname?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        NoticeResBody: {
            id?: string;
            title?: string;
            content?: string;
            admin?: components["schemas"]["AdminResBody"];
            /** Format: date-time */
            createdAt?: string;
        };
        RsDataNoticeResBody: {
            code: string;
            message: string;
            data: components["schemas"]["NoticeResBody"];
        };
        SignUpUserForm: {
            username?: string;
            password?: string;
            email: string;
            nickname?: string;
            address?: string;
            profileUrl?: string;
        };
        RefreshUserForm: {
            refreshToken: string;
        };
        RsDataString: {
            code: string;
            message: string;
            data: string;
        };
        LoginUserForm: {
            username: string;
            password: string;
        };
        LoginUserDto: {
            accessToken?: string;
            refreshToken?: string;
            item?: components["schemas"]["UserDto"];
        };
        RsDataLoginUserDto: {
            code: string;
            message: string;
            data: components["schemas"]["LoginUserDto"];
        };
        EmailCodeRequest: {
            email?: string;
        };
        VerifyCodeRequest: {
            email?: string;
            code?: string;
        };
        ProductPostWriteForm: {
            productName: string;
            /** Format: int32 */
            productPrice: number;
            title: string;
            content: string;
            categoryIds: number[];
            imageUrlList: string[];
            /** Format: float */
            latitude: number;
            /** Format: float */
            longitude: number;
        };
        WriteCommentReqBody: {
            content?: string;
        };
        RsDataWriteCommentResBody: {
            code: string;
            message: string;
            data: components["schemas"]["WriteCommentResBody"];
        };
        WriteCommentResBody: {
            id?: string;
            content?: string;
            author?: components["schemas"]["UserDto"];
        };
        PurchaseItemReqDto: {
            productId?: string;
        };
        PaymentDto: {
            id?: string;
            buyerId?: string;
            /** Format: int32 */
            totalPrice?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            /** @enum {string} */
            status?: "IN_PROGRESS" | "DONE" | "ABORTED";
        };
        RsDataPaymentDto: {
            code: string;
            message: string;
            data: components["schemas"]["PaymentDto"];
        };
        ChatRoom: {
            id?: string;
            roomId?: string;
            name?: string;
            sender?: string;
            receiver?: string;
            client?: string;
            /** Format: int64 */
            userCount?: number;
        };
        RsDataChatRoom: {
            code: string;
            message: string;
            data: components["schemas"]["ChatRoom"];
        };
        /** @description 공지사항 등록 요청 바디 */
        BanReqBody: {
            reason: string;
        };
        BanResBody: {
            banListId?: string;
            userId?: string;
            reason?: string;
            /** Format: int32 */
            banCount?: number;
            /** Format: date-time */
            startDate?: string;
            /** Format: date-time */
            endDate?: string;
        };
        RsDataBanResBody: {
            code: string;
            message: string;
            data: components["schemas"]["BanResBody"];
        };
        /** @description 공지사항 등록 body */
        NoticeReqBody: {
            title: string;
            content: string;
        };
        PageDtoPreviewPostResponse: {
            items: components["schemas"]["PreviewPostResponse"][];
            /** Format: int32 */
            totalPages: number;
            /** Format: int32 */
            totalItems: number;
            /** Format: int32 */
            curPageNo: number;
            /** Format: int32 */
            pageSize: number;
        };
        PreviewPostResponse: {
            id?: string;
            productName?: string;
            /** Format: int32 */
            productPrice?: number;
            title?: string;
            writerId?: string;
            writerName?: string;
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            thumbNail?: string;
            /** Format: date-time */
            createdAt?: string;
            imageUrls?: string;
            /** Format: int32 */
            viewCount?: number;
            /** Format: int32 */
            likedCount?: number;
            /** @enum {string} */
            status?: "RESERVED" | "AVAILABLE" | "PURCHASED";
        };
        RsDataPageDtoPreviewPostResponse: {
            code: string;
            message: string;
            data: components["schemas"]["PageDtoPreviewPostResponse"];
        };
        RsDataListPreviewPostResponse: {
            code: string;
            message: string;
            data: components["schemas"]["PreviewPostResponse"][];
        };
        RsDataListProductPostResponse: {
            code: string;
            message: string;
            data: components["schemas"]["ProductPostResponse"][];
        };
        PageDtoProductPostResponse: {
            items: components["schemas"]["ProductPostResponse"][];
            /** Format: int32 */
            totalPages: number;
            /** Format: int32 */
            totalItems: number;
            /** Format: int32 */
            curPageNo: number;
            /** Format: int32 */
            pageSize: number;
        };
        RsDataPageDtoProductPostResponse: {
            code: string;
            message: string;
            data: components["schemas"]["PageDtoProductPostResponse"];
        };
        RsDataBoolean: {
            code: string;
            message: string;
            data: boolean;
        };
        PaymentMetaData: {
            paymentId?: string;
            /** Format: int32 */
            amount?: number;
        };
        RsDataPaymentMetaData: {
            code: string;
            message: string;
            data: components["schemas"]["PaymentMetaData"];
        };
        AccessProvider: {
            name?: string;
            token?: string;
        };
        RsDataAccessProvider: {
            code: string;
            message: string;
            data: components["schemas"]["AccessProvider"];
        };
        ChatRoomDto: {
            postId?: string;
            roomId?: string;
            name?: string;
            /** Format: int64 */
            userCount?: number;
        };
        RsDataListChatRoomDto: {
            code: string;
            message: string;
            data: components["schemas"]["ChatRoomDto"][];
        };
        MessageDto: {
            sender?: string;
            message?: string;
            image?: string;
            timestamp?: string;
        };
        RsDataListMessageDto: {
            code: string;
            message: string;
            data: components["schemas"]["MessageDto"][];
        };
        RsDataListCategory: {
            code: string;
            message: string;
            data: components["schemas"]["Category"][];
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageUserDto: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["UserDto"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
            paged?: boolean;
            /** Format: int32 */
            pageSize?: number;
            /** Format: int32 */
            pageNumber?: number;
        };
        RsDataPageUserDto: {
            code: string;
            message: string;
            data: components["schemas"]["PageUserDto"];
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        PageNoticeResBody: {
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["NoticeResBody"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            first?: boolean;
            last?: boolean;
            /** Format: int32 */
            numberOfElements?: number;
            empty?: boolean;
        };
        RsDataPageNoticeResBody: {
            code: string;
            message: string;
            data: components["schemas"]["PageNoticeResBody"];
        };
        RsDataListNoticeResBody: {
            code: string;
            message: string;
            data: components["schemas"]["NoticeResBody"][];
        };
        RsDataObject: {
            code: string;
            message: string;
            data: Record<string, never>;
        };
        Empty: Record<string, never>;
        RsDataEmpty: {
            code: string;
            message: string;
            data: components["schemas"]["Empty"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUserDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUserDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataObject"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    updateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "comment-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUpdateCommentResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "comment-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 상품 게시글 id
                 * @example ppost-f90sdf8-sd8fu7sd-ds8uf9
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    modify: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 상품 게시글 id
                 * @example ppost-fsiodf-21edd-fd2c1
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPostModifyForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 상품 게시글 id
                 * @example ppost-2ji109-fe3sfd-3fsdf
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataEmpty"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    grantAdmin: {
        parameters: {
            query: {
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUser"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    updateNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "notice-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoticeReq"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataNoticeResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "notice-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpUserForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataUserDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshUserForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataString"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataLoginUserDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    sendAuthenticationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    verifyAuthenticationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": string;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getPosts: {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지에 포함된 아이템 개수 */
                pageSize?: number;
                /** @description 검색 키워드 */
                keyword?: string;
                /**
                 * @description 정렬 순서. desc:내림차순, asc:오름차순
                 * @example desc
                 */
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageDtoPreviewPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPostWriteForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    writeComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 작성할 상품 게시글 id */
                "post-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteCommentReqBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataWriteCommentResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    likePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 상품 게시글 id
                 * @example ppost-2ji109-fe3sfd-3fsdf
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    checkPurchased: {
        parameters: {
            query: {
                "post-id": string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataBoolean"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    purchaseItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseItemReqDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPaymentDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    rooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": string;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query: {
                /**
                 * @description 상품 게시글 아이디
                 * @example ppost-fkkdsjf9adsa-ds8fdfsdf-289103yd
                 */
                postId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataChatRoom"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    createRoomAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 관리자 id
                 * @example user-1231jkj-g04hi8gah-123hixfdh9
                 */
                adminId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataChatRoom"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    banUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 유저 id */
                "user-id": string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BanReqBody"];
            };
        };
        responses: {
            /** @description 유저 정지 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataBanResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    unBanUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                "user-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getNotices: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageNoticeResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    writeNotice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticeReqBody"];
            };
        };
        responses: {
            /** @description 공지사항 등록 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataNoticeResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getRecentlyViewPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListPreviewPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMyPosts: {
        parameters: {
            query?: {
                /** @description 페이지 번호 */
                page?: number;
                /** @description 페이지 내 아이템 개수 */
                pageSize?: number;
                /** @description 정렬 순서 */
                sort?: string;
                status?: "RESERVED" | "AVAILABLE" | "PURCHASED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageDtoPreviewPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMySales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMyPurchases: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageDtoProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMyFavorites: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageDtoProductPostResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    requestPayment: {
        parameters: {
            query: {
                /** @description 결제 id */
                orderId: string;
                /** @description PG사에서 생성한 paymentKey */
                paymentKey: string;
                /** @description 총 구매 가격 */
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    saveMetaData: {
        parameters: {
            query: {
                /** @description 구매할 상품 게시글 id */
                id: string;
                /** @description 총 결제 금액 */
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPaymentMetaData"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getUserInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataAccessProvider"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    findChatRooms: {
        parameters: {
            query: {
                /**
                 * @description 찾으려는 채팅방에 속한 유저의 ID
                 * @example user-12k3j-sjdfi2jj-431iojr124io1
                 */
                receiver: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataString"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getUserRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListChatRoomDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    showRoomDetailPage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": string;
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query: {
                /**
                 * @description 채팅방 id
                 * @example 123
                 */
                roomId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListMessageDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deleteRoom: {
        parameters: {
            query: {
                /**
                 * @description 채팅방 id
                 * @example 123
                 */
                roomId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataString"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListCategory"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getUserList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataPageUserDto"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    getLatestNotices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 최신 공지사항 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataListNoticeResBody"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description post id */
                "post-id": string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 게시글 삭제 성공 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json;charset=UTF-8": components["schemas"]["RsDataVoid"];
                };
            };
        };
    };
}
