spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: f2f7512ce923d4e37181ceb038246783

custom:
  jwt:
    secret-key: abcdefghijklmnopqrstuvwxyz1234567890abcdefghijklmnopqrstuvwxyz1234567890
    expire-seconds: "#{60 * 30}"
  toss:
    payment:
      secret: dGVzdF9za180eUtlcTViZ3JwMnE2QmtNMGxtcDNHWDBselc2Og==