custom:
  jwt:
    secret-key: ${JWT_SECRET}
    expire-seconds: "#{60 * 30}"          # accessToken 만료 시간 1시간
  refreshToken:
    expire-seconds: "#{60 * 60 * 24 * 7}" # refreshToken 만료 시간 7일
  toss:
    payment:
      secret: ${TOSS_SECRET}
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gilgebolsai@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      auth-code-expiration-second: "#{3 * 60}"  # 이메일 인증 코드의 만료 시간 3분