server:
  port: 8080

custom:
  server:
    host: localhost
  front:
    host: localhost
    port: 3000

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false

  output:
    ansi:
      enabled: always

  data:
    redis:
      port: 6379
      host: localhost

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000                     # 클라이언트 -> SMTP 서버 연결 대기 시간
          timeout: 5000                                # 클라이언트 <- SMTP 서버 응답 대기 시간
          write-timeout: 5000                          # 클라이언트 작업 완료 대기 시간

  web:
    resources:
      static-locations: classpath:/static/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.security: DEBUG

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
