custom:
  jwt:
    secret-key: ${JWT_SECRET}
    expire-seconds: "#{60* 60}"
  refreshToken:
    expire-seconds: "#{60 * 60 * 24 * 7}"
  toss:
    payment:
      secret: ${TOSS_SECRET}
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gilgebolsai@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      auth-code-expiration-second: 300  # 이메일 인증 코드의 만료 시간 3분

pop3:
  host: pop.gmail.com
  port: 995
  protocol: pop3s
  folder: INBOX
  username: gilgebolsai@gmail.com
  password: ${MAIL_PASSWORD}
  until-time: 120 # 최근 2분 이내의 이메일만을 검증함

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}  # 버킷 이름을 환경 변수로 설정
    credentials:
      access-key: ${AWS_ACCESS_KEY}   # 액세스 키를 환경 변수로 설정
      secret-key: ${AWS_SECRET_KEY}    # 비밀 키를 환경 변수로 설정
    region:
      static: ap-northeast-2            # 지역은 환경 변수를 사용하지 않도록 고정
      auto: false
    stack:
      auto: false
